services:
  - type: web
    name: crud-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application --chdir project
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: PYTHON_VERSION
        value: 3.9
